// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Q0CNf3FAUvRJydUiJ5yJivnzW9QsWdw',
    appId: '1:856526335102:web:06fd9e37afec1a9589bc2f',
    messagingSenderId: '856526335102',
    projectId: 'atvd2-pdm',
    authDomain: 'atvd2-pdm.firebaseapp.com',
    storageBucket: 'atvd2-pdm.appspot.com',
    measurementId: 'G-2H4C615QLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPTyuY_5B2sxOSVPscm31b8YI_KGSjwuM',
    appId: '1:856526335102:android:158ad9dd1e49ad9389bc2f',
    messagingSenderId: '856526335102',
    projectId: 'atvd2-pdm',
    storageBucket: 'atvd2-pdm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAitL97NZL9G4pyII0Vk_k3_Pho5ok4di0',
    appId: '1:856526335102:ios:dbf4aa3f98cd3c7789bc2f',
    messagingSenderId: '856526335102',
    projectId: 'atvd2-pdm',
    storageBucket: 'atvd2-pdm.appspot.com',
    iosClientId: '856526335102-iovur9tvetrc0lhtpprr85cuk8s9nbp7.apps.googleusercontent.com',
    iosBundleId: 'y',
  );
}
